describe the abcd archive connection
umr-dbs/vat-docs pull request #11
Opened 2024-11-15 11:53 UTC by ChristianBeilschmidt

2024-11-15 11:53 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [VAT-Docs: 2p](https://trello.com/c/TDjNe4ri/1763-vat-docs-2p)

2024-11-18 09:41 UTC, dbrandenstein requested changes

2024-11-18 09:41 UTC, dbrandenstein commented on src/features/abcd.md
> +Some ABCD datasets contain linkts to multimedia items.
links

2024-11-18 09:41 UTC, dbrandenstein commented on src/features/abcd.md
> +The data table will show at most 3 links for clustered occurrences.
three

2024-11-19 09:05 UTC, ChristianBeilschmidt commented on src/features/abcd.md
> +The data table will show at most 3 links for clustered occurrences.
[a8bc18d](https://github.com/umr-dbs/vat-docs/pull/11/commits/a8bc18d4efa5839ccf6113038bd1e8d5681892de)

2024-11-19 09:05 UTC, ChristianBeilschmidt commented on src/features/abcd.md
> +Some ABCD datasets contain linkts to multimedia items.
[a8bc18d](https://github.com/umr-dbs/vat-docs/pull/11/commits/a8bc18d4efa5839ccf6113038bd1e8d5681892de)

2024-11-19 09:21 UTC, dbrandenstein approved these changes

2024-11-19 11:30 UTC, merged